// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpaceCropAPI.Data;

#nullable disable

namespace SpaceCropAPI.Migrations
{
    [DbContext(typeof(SpaceCropContext))]
    partial class SpaceCropContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("SpaceCropAPI.Models.AcaoAlerta", b =>
            {
                b.Property<long>("IdAcao")
                    .HasColumnType("NUMBER(19)")
                    .HasColumnName("ID_ACAO");

                b.Property<string>("DsAcaoTomada")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("NVARCHAR2(500)")
                    .HasColumnName("DS_ACAO_TOMADA");

                b.Property<DateTime>("DtAcao")
                    .HasColumnType("DATE")
                    .HasColumnName("DT_ACAO");

                b.Property<long>("IdAlerta")
                    .HasColumnType("NUMBER(19)")
                    .HasColumnName("ID_ALERTA");

                b.Property<long>("IdUsuario")
                    .HasColumnType("NUMBER(19)")
                    .HasColumnName("ID_USUARIO");

                b.HasKey("IdAcao");

                b.HasIndex("IdAlerta").HasDatabaseName("IX_TB_ACAO_ALERTA_ID_ALERTA");
                b.HasIndex("IdUsuario").HasDatabaseName("IX_TB_ACAO_ALERTA_ID_USUARIO");

                b.ToTable("TB_ACAO_ALERTA");
            });

            modelBuilder.Entity("SpaceCropAPI.Models.Alerta", b =>
            {
                b.Property<long>("IdAlerta")
                    .HasColumnType("NUMBER(19)")
                    .HasColumnName("ID_ALERTA");

                b.Property<DateTime>("DtAlerta")
                    .HasColumnType("DATE")
                    .HasColumnName("DT_ALERTA");

                b.Property<string>("FlResolvido")
                    .IsRequired()
                    .HasMaxLength(1)
                    .HasColumnType("NVARCHAR2(1)")
                    .HasColumnName("FL_RESOLVIDO");

                b.Property<long>("IdLeitura")
                    .HasColumnType("NUMBER(19)")
                    .HasColumnName("ID_LEITURA");

                b.Property<long>("IdTipoAlerta")
                    .HasColumnType("NUMBER(19)")
                    .HasColumnName("ID_TIPO_ALERTA");

                b.Property<long>("IdUsuario")
                    .HasColumnType("NUMBER(19)")
                    .HasColumnName("ID_USUARIO");

                b.HasKey("IdAlerta");

                b.HasIndex("IdLeitura").HasDatabaseName("IX_TB_ALERTA_ID_LEITURA");
                b.HasIndex("IdTipoAlerta").HasDatabaseName("IX_TB_ALERTA_ID_TIPO_ALERTA");
                b.HasIndex("IdUsuario").HasDatabaseName("IX_TB_ALERTA_ID_USUARIO");

                b.ToTable("TB_ALERTA");
            });

            modelBuilder.Entity("SpaceCropAPI.Models.Fazenda", b =>
            {
                b.Property<long>("IdFazenda")
                    .HasColumnType("NUMBER(19)")
                    .HasColumnName("ID_FAZENDA");

                b.Property<string>("DsCidade")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("NVARCHAR2(100)")
                    .HasColumnName("DS_CIDADE");

                b.Property<string>("DsEstado")
                    .IsRequired()
                    .HasMaxLength(2)
                    .HasColumnType("NVARCHAR2(2)")
                    .HasColumnName("DS_ESTADO");

                b.Property<long>("IdUsuario")
                    .HasColumnType("NUMBER(19)")
                    .HasColumnName("ID_USUARIO");

                b.Property<string>("NmFazenda")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("NVARCHAR2(150)")
                    .HasColumnName("NM_FAZENDA");

                b.Property<decimal>("NrAreaHectares")
                    .HasPrecision(10, 2)
                    .HasColumnType("NUMBER(10,2)")
                    .HasColumnName("NR_AREA_HECTARES");

                b.HasKey("IdFazenda");

                b.HasIndex("IdUsuario").HasDatabaseName("IX_TB_FAZENDA_ID_USUARIO");

                b.ToTable("TB_FAZENDA");
            });

            modelBuilder.Entity("SpaceCropAPI.Models.LeituraSatelite", b =>
            {
                b.Property<long>("IdLeitura")
                    .HasColumnType("NUMBER(19)")
                    .HasColumnName("ID_LEITURA");

                b.Property<DateTime>("DtLeitura")
                    .HasColumnType("DATE")
                    .HasColumnName("DT_LEITURA");

                b.Property<string>("FlAnomalia")
                    .IsRequired()
                    .HasMaxLength(1)
                    .HasColumnType("NVARCHAR2(1)")
                    .HasColumnName("FL_ANOMALIA");

                b.Property<long>("IdFazenda")
                    .HasColumnType("NUMBER(19)")
                    .HasColumnName("ID_FAZENDA");

                b.Property<long?>("IdSetor")
                    .HasColumnType("NUMBER(19)")
                    .HasColumnName("ID_SETOR");

                b.Property<long>("IdSensorOrbital")
                    .HasColumnType("NUMBER(19)")
                    .HasColumnName("ID_SENSOR_ORBITAL");

                b.Property<decimal>("NrValor")
                    .HasPrecision(8, 2)
                    .HasColumnType("NUMBER(8,2)")
                    .HasColumnName("NR_VALOR");

                b.HasKey("IdLeitura");

                b.HasIndex("IdFazenda").HasDatabaseName("IX_TB_LEITURA_SATELITE_ID_FAZENDA");
                b.HasIndex("IdSetor").HasDatabaseName("IX_TB_LEITURA_SATELITE_ID_SETOR");
                b.HasIndex("IdSensorOrbital").HasDatabaseName("IX_TB_LEITURA_SATELITE_ID_SENSOR_ORBITAL");

                b.ToTable("TB_LEITURA_SATELITE");
            });

            modelBuilder.Entity("SpaceCropAPI.Models.Satelite", b =>
            {
                b.Property<long>("IdSatelite")
                    .HasColumnType("NUMBER(19)")
                    .HasColumnName("ID_SATELITE");

                b.Property<string>("DsOperador")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("NVARCHAR2(100)")
                    .HasColumnName("DS_OPERADOR");

                b.Property<string>("FlAtivo")
                    .IsRequired()
                    .HasMaxLength(1)
                    .HasColumnType("NVARCHAR2(1)")
                    .HasColumnName("FL_ATIVO");

                b.Property<string>("NmSatelite")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("NVARCHAR2(100)")
                    .HasColumnName("NM_SATELITE");

                b.HasKey("IdSatelite");

                b.ToTable("TB_SATELITE");
            });

            modelBuilder.Entity("SpaceCropAPI.Models.SensorOrbital", b =>
            {
                b.Property<long>("IdSensorOrbital")
                    .HasColumnType("NUMBER(19)")
                    .HasColumnName("ID_SENSOR_ORBITAL");

                b.Property<string>("FlAtivo")
                    .IsRequired()
                    .HasMaxLength(1)
                    .HasColumnType("NVARCHAR2(1)")
                    .HasColumnName("FL_ATIVO");

                b.Property<long>("IdSatelite")
                    .HasColumnType("NUMBER(19)")
                    .HasColumnName("ID_SATELITE");

                b.Property<long>("IdTipoSensor")
                    .HasColumnType("NUMBER(19)")
                    .HasColumnName("ID_TIPO_SENSOR");

                b.Property<string>("NmSensor")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("NVARCHAR2(100)")
                    .HasColumnName("NM_SENSOR");

                b.HasKey("IdSensorOrbital");

                b.HasIndex("IdSatelite").HasDatabaseName("IX_TB_SENSOR_ORBITAL_ID_SATELITE");
                b.HasIndex("IdTipoSensor").HasDatabaseName("IX_TB_SENSOR_ORBITAL_ID_TIPO_SENSOR");

                b.ToTable("TB_SENSOR_ORBITAL");
            });

            modelBuilder.Entity("SpaceCropAPI.Models.SetorPlantio", b =>
            {
                b.Property<long>("IdSetor")
                    .HasColumnType("NUMBER(19)")
                    .HasColumnName("ID_SETOR");

                b.Property<string>("DsCultura")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("NVARCHAR2(100)")
                    .HasColumnName("DS_CULTURA");

                b.Property<long>("IdFazenda")
                    .HasColumnType("NUMBER(19)")
                    .HasColumnName("ID_FAZENDA");

                b.Property<string>("NmSetor")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("NVARCHAR2(100)")
                    .HasColumnName("NM_SETOR");

                b.Property<decimal>("NrAreaHectares")
                    .HasPrecision(10, 2)
                    .HasColumnType("NUMBER(10,2)")
                    .HasColumnName("NR_AREA_HECTARES");

                b.HasKey("IdSetor");

                b.HasIndex("IdFazenda").HasDatabaseName("IX_TB_SETOR_PLANTIO_ID_FAZENDA");

                b.ToTable("TB_SETOR_PLANTIO");
            });

            modelBuilder.Entity("SpaceCropAPI.Models.TipoAlerta", b =>
            {
                b.Property<long>("IdTipoAlerta")
                    .HasColumnType("NUMBER(19)")
                    .HasColumnName("ID_TIPO_ALERTA");

                b.Property<string>("DsSeveridade")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("NVARCHAR2(20)")
                    .HasColumnName("DS_SEVERIDADE");

                b.Property<string>("FlRequerAcao")
                    .IsRequired()
                    .HasMaxLength(1)
                    .HasColumnType("NVARCHAR2(1)")
                    .HasColumnName("FL_REQUER_ACAO");

                b.Property<string>("NmTipoAlerta")
                    .IsRequired()
                    .HasMaxLength(80)
                    .HasColumnType("NVARCHAR2(80)")
                    .HasColumnName("NM_TIPO_ALERTA");

                b.HasKey("IdTipoAlerta");

                b.ToTable("TB_TIPO_ALERTA");
            });

            modelBuilder.Entity("SpaceCropAPI.Models.TipoSensor", b =>
            {
                b.Property<long>("IdTipoSensor")
                    .HasColumnType("NUMBER(19)")
                    .HasColumnName("ID_TIPO_SENSOR");

                b.Property<string>("DsUnidadeMedida")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("NVARCHAR2(20)")
                    .HasColumnName("DS_UNIDADE_MEDIDA");

                b.Property<string>("NmTipo")
                    .IsRequired()
                    .HasMaxLength(80)
                    .HasColumnType("NVARCHAR2(80)")
                    .HasColumnName("NM_TIPO");

                b.Property<decimal>("NrValorCritico")
                    .HasPrecision(8, 2)
                    .HasColumnType("NUMBER(8,2)")
                    .HasColumnName("NR_VALOR_CRITICO");

                b.HasKey("IdTipoSensor");

                b.ToTable("TB_TIPO_SENSOR");
            });

            modelBuilder.Entity("SpaceCropAPI.Models.Usuario", b =>
            {
                b.Property<long>("IdUsuario")
                    .HasColumnType("NUMBER(19)")
                    .HasColumnName("ID_USUARIO");

                b.Property<string>("DsEmail")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("NVARCHAR2(150)")
                    .HasColumnName("DS_EMAIL");

                b.Property<string>("DsSenhaHash")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("NVARCHAR2(255)")
                    .HasColumnName("DS_SENHA_HASH");

                b.Property<string>("NmUsuario")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("NVARCHAR2(100)")
                    .HasColumnName("NM_USUARIO");

                b.HasKey("IdUsuario");

                b.HasIndex("DsEmail")
                    .IsUnique()
                    .HasDatabaseName("IX_TB_USUARIO_DS_EMAIL");

                b.ToTable("TB_USUARIO");
            });

            // Relacionamentos
            modelBuilder.Entity("SpaceCropAPI.Models.AcaoAlerta", b =>
            {
                b.HasOne("SpaceCropAPI.Models.Alerta", "Alerta")
                    .WithMany("Acoes")
                    .HasForeignKey("IdAlerta")
                    .OnDelete(DeleteBehavior.Restrict);

                b.HasOne("SpaceCropAPI.Models.Usuario", "Usuario")
                    .WithMany("AcoesAlerta")
                    .HasForeignKey("IdUsuario")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("Alerta");
                b.Navigation("Usuario");
            });

            modelBuilder.Entity("SpaceCropAPI.Models.Alerta", b =>
            {
                b.HasOne("SpaceCropAPI.Models.LeituraSatelite", "Leitura")
                    .WithMany("Alertas")
                    .HasForeignKey("IdLeitura")
                    .OnDelete(DeleteBehavior.Restrict);

                b.HasOne("SpaceCropAPI.Models.TipoAlerta", "TipoAlerta")
                    .WithMany("Alertas")
                    .HasForeignKey("IdTipoAlerta")
                    .OnDelete(DeleteBehavior.Restrict);

                b.HasOne("SpaceCropAPI.Models.Usuario", "Usuario")
                    .WithMany("Alertas")
                    .HasForeignKey("IdUsuario")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("Leitura");
                b.Navigation("TipoAlerta");
                b.Navigation("Usuario");
            });

            modelBuilder.Entity("SpaceCropAPI.Models.Fazenda", b =>
            {
                b.HasOne("SpaceCropAPI.Models.Usuario", "Usuario")
                    .WithMany("Fazendas")
                    .HasForeignKey("IdUsuario")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("Usuario");
            });

            modelBuilder.Entity("SpaceCropAPI.Models.LeituraSatelite", b =>
            {
                b.HasOne("SpaceCropAPI.Models.Fazenda", "Fazenda")
                    .WithMany("Leituras")
                    .HasForeignKey("IdFazenda")
                    .OnDelete(DeleteBehavior.Restrict);

                b.HasOne("SpaceCropAPI.Models.SetorPlantio", "Setor")
                    .WithMany("Leituras")
                    .HasForeignKey("IdSetor")
                    .OnDelete(DeleteBehavior.Restrict);

                b.HasOne("SpaceCropAPI.Models.SensorOrbital", "SensorOrbital")
                    .WithMany("Leituras")
                    .HasForeignKey("IdSensorOrbital")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("Fazenda");
                b.Navigation("Setor");
                b.Navigation("SensorOrbital");
            });

            modelBuilder.Entity("SpaceCropAPI.Models.SensorOrbital", b =>
            {
                b.HasOne("SpaceCropAPI.Models.Satelite", "Satelite")
                    .WithMany("Sensores")
                    .HasForeignKey("IdSatelite")
                    .OnDelete(DeleteBehavior.Restrict);

                b.HasOne("SpaceCropAPI.Models.TipoSensor", "TipoSensor")
                    .WithMany("Sensores")
                    .HasForeignKey("IdTipoSensor")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("Satelite");
                b.Navigation("TipoSensor");
            });

            modelBuilder.Entity("SpaceCropAPI.Models.SetorPlantio", b =>
            {
                b.HasOne("SpaceCropAPI.Models.Fazenda", "Fazenda")
                    .WithMany("SetoresPlantio")
                    .HasForeignKey("IdFazenda")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("Fazenda");
            });

            modelBuilder.Entity("SpaceCropAPI.Models.Alerta", b =>
            {
                b.Navigation("Acoes");
            });

            modelBuilder.Entity("SpaceCropAPI.Models.Fazenda", b =>
            {
                b.Navigation("Leituras");
                b.Navigation("SetoresPlantio");
            });

            modelBuilder.Entity("SpaceCropAPI.Models.LeituraSatelite", b =>
            {
                b.Navigation("Alertas");
            });

            modelBuilder.Entity("SpaceCropAPI.Models.Satelite", b =>
            {
                b.Navigation("Sensores");
            });

            modelBuilder.Entity("SpaceCropAPI.Models.SensorOrbital", b =>
            {
                b.Navigation("Leituras");
            });

            modelBuilder.Entity("SpaceCropAPI.Models.SetorPlantio", b =>
            {
                b.Navigation("Leituras");
            });

            modelBuilder.Entity("SpaceCropAPI.Models.TipoAlerta", b =>
            {
                b.Navigation("Alertas");
            });

            modelBuilder.Entity("SpaceCropAPI.Models.TipoSensor", b =>
            {
                b.Navigation("Sensores");
            });

            modelBuilder.Entity("SpaceCropAPI.Models.Usuario", b =>
            {
                b.Navigation("AcoesAlerta");
                b.Navigation("Alertas");
                b.Navigation("Fazendas");
            });
#pragma warning restore 612, 618
        }
    }
}
